### ISSUE TITLE
Make the new "(optional)" text optional

### ISSUE THREAD

**Issue by chescales** [chrisdev/django-foundation-formtags#67]
Hi there! Thanks Chris for the work on the app ;)

I updated the app from 0.0.7 to 0.0.9 and suddenly all kinds of `(optional)` words started appearing in my website's forms. Is there any possibility to make those optional? I'm going to downgrade the app to 0.0.7 again for now, but in the future would prefer not to show that text to my users.

Thanks!

https://github.com/chrisdev/django-foundation-formtags/blob/7c2395d5f0b0962972dc9da2c1de2db5e8dcb050/foundation_formtags/templates/foundation_formtags/foundation_form_field.html#L20-L22

**Comment by chrisdev** [comment]
@chescales @Parbhat I this was contributed by in this  [commit](https://github.com/chrisdev/django-foundation-formtags/commit/f8765092ba954a84da23813616d8b11b95244c37) as way to improve accessibility.  I found this [article](https://www.formulate.com.au/blog/required-versus-optional-fields-new-standard) that make the case for *optional* instead of `* `required. 

However, I agree with @chescales that our implementation was not well thought out. For one thing, we failed to consider internationalisation/localization implications of using an English word *optional* instead of `*`

Actually,  article makes a number other useful recommendations and  *optional* is only one of the of them. 

1. Have an instruction, at the top of each screen, that says: “All questions must be answered, unless marked (optional).” 
2. Do not have any visual markings against required questions.
3.  Add “(optional)” to the end of the label for every optional question
4. semantically mark required fields with the HTML5 required attribute on the input element and/or set the property aria-required to true
5.  make the text “(optional)” a less prominent colour (e.g. lighter grey like #646464), so it contrasts slightly with other form elements (but still constrasts sufficiently with the background). 

I think the @chescales is correct about [2]. Many devs will want to continue to use  `*` for required fields and we should support them. We have a setting, say `USE_REQUIRED` which will make this happen. Maybe this should be on by default. 

We definitely need to implement [4] http://www.w3.org/TR/html5/forms.html#attr-input-required
wether we are using *optional* or `*`

If we are using the *optimal* approach we need to implement [5]

**Comment by chescales** [comment]
Definitely @chrisdev, [4] should be a must. About marking required or optional fields with extra strings (be it a '*' or a '(optional)') I think we could leave that to each coder to decide, as it may go or not with the rest of the site UX. 

Maybe have 2 settings that allow personalising those two strings, and have as default behaviour '*' for required and empty string for optionals? Or even html snippets like `SUFFIX_OPTIONAL = '<small>(optional)</small>'`

Being the UX of each one of the sites so different, I wouldn't try to impose a way of marking required/optional from a third party app, as it may be more of a problem than a solution for your users.

**Comment by Parbhat** [comment]
@chrisdev @chescales Yes, we need to give users option to use `*` or `optional`. We can use a `Flag` like `FOUNDATION_FORMTAGS_USE_OPTIONAL` which defaults to `False`. The user can set it to `True` in its Django `settings`, if he/she wants to use `Optional`. For the point `[4]`, Django in latest versions automatically adds `html5` required attribute to fields.
